export const banner = `trending/all/day?api_key=${process.env.REACT_APP_API_KEY}`
export const originals = `discover/tv?api_key=${process.env.REACT_APP_API_KEY}&with_networks=213`
export const comedy = `discover/movie?api_key=${process.env.REACT_APP_API_KEY}&language=en-US&page=3&with_genres=35`
export const crime = `discover/movie?api_key=${process.env.REACT_APP_API_KEY}&language=en-US&page=1&with_genres=80`
export const family = `discover/movie?api_key=${process.env.REACT_APP_API_KEY}&language=en-US&page=1&with_genres=10751`
export const fantasy = `discover/movie?api_key=${process.env.REACT_APP_API_KEY}&language=en-US&page=6&with_genres=14`
export const horror = `discover/movie?api_key=${process.env.REACT_APP_API_KEY}&language=en-US&page=1&with_genres=27`
export const mystery = `discover/movie?api_key=${process.env.REACT_APP_API_KEY}&language=en-US&page=1&with_genres=9648`
export const sciencefiction = `discover/movie?api_key=${process.env.REACT_APP_API_KEY}&language=en-US&sort_by=release_date.de&page=3&with_genres=878`
export const thriller = `discover/movie?api_key=${process.env.REACT_APP_API_KEY}&language=en-US&page=10&with_genres=53&sort_by=release_date.de`
export const music = `discover/movie?api_key=${process.env.REACT_APP_API_KEY}&language=en-US&page=1&with_genres=10402&sort_by=release_date.de`
export const western = `discover/movie?api_key=${process.env.REACT_APP_API_KEY}&language=en-US&page=2&with_genres=37`
export const toprated = `movie/top_rated?api_key=${process.env.REACT_APP_API_KEY}&language=en-US&page=1`
export const trending = `trending/all/day?api_key=${process.env.REACT_APP_API_KEY}`
export const popular = `movie/popular?api_key=${process.env.REACT_APP_API_KEY}&language=en-US&page=1`
export const upcoming = `movie/upcoming?api_key=${process.env.REACT_APP_API_KEY}&language=en-US&page=1`